### ISSUE TITLE
Broker pipe error

### ISSUE THREAD

**Issue by quantumpanic** [fonic/wcdatool#10]
running any of the shell scripts causes a broken pipe error on VS Code:

> [21644:0115/132121.563:ERROR:broker_win.cc(56)] Error reading broker pipe: The pipe has been ended. (0x6D)
> [6072:0115/132122.561:ERROR:broker_win.cc(56)] Error reading broker pipe: The pipe has been ended. (0x6D)
> [9756:0115/132123.310:ERROR:broker_win.cc(56)] Error reading broker pipe: The pipe has been ended. (0x6D)

**Comment by fonic** [comment]
Not sure what _VS Code_ is doing there. I doubt that this has anything to do with the scripts themselves as there are neither any Bash-related errors nor any output lines generated by the scripts visible.

Let me know if you find out what's going on there.

**Comment by fonic** [comment]
Closed due to inactivity.
